### ISSUE TITLE
after the update to 2.8.0, the following error occurs

### ISSUE THREAD

**Issue by det-box** [naofireblade/homebridge-weather-plus#73]
Hallo,
after the update to 2.8.0, the following error occurs

`Sep 15 11:26:53 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] Registering platform 'homebridge-weather-plus.WeatherPlus'
Sep 15 11:26:53 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] ---
Sep 15 11:26:53 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] Loading 2 platforms...
Sep 15 11:26:53 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] [Wetter-plus] Initializing WeatherPlus platform...
Sep 15 11:26:53 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] TypeError: city.toLowerCase is not a function
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at Object.weather.setCity (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/openweather-apis/index.js:29:43)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at new OpenWeatherMapAPI (/usr/local/lib/node_modules/homebridge-weather-plus/api/openweathermap.js:19:28)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at WeatherStationPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/index.js:103:19)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at Array.forEach (<anonymous>)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at new WeatherStationPlatform (/usr/local/lib/node_modules/homebridge-weather-plus/index.js:87:23)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Sep 15 11:26:53 hbridge3 homebridge[2120]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 15 11:26:54 hbridge3 homebridge[2120]:     at Module._compile (internal/modules/cjs/loader.js:936:30)
Sep 15 11:26:54 hbridge3 homebridge[2120]: [2019-9-15 11:26:53] Got SIGTERM, shutting down Homebridge...
`

How can I fix this error?

Here my configuration:
`        {
            "platform": "WeatherPlus",
            "name": "Wetter-plus",
            "service": "openweathermap",
            "key": "xxxxxxxxxxxxxxxxxxx",
            "location": 2940132,
            "locationCity": "Chemnitz, DE",
            "locationGeo": [
                50.8323,
                12.9253
            ],
            "language": "de",
            "forecast": [
                1,
                2,
                3,
                4,
                5
            ]
        },
`
I'm going back to 2.7.2, everything's fine.

Thanks

**Comment by JacVid** [comment]
I have issues as well !

How do you go back to 2.7.2 ?

**Comment by monsterciattolo** [comment]
me too

**Comment by paskovitch** [comment]
@JacVid   sudo npm install -g --unsafe-perm homebridge-weather-plus@2.7.2

**Comment by JacVid** [comment]
> @JacVid sudo npm install -g --unsafe-perm homebridge-weather-plus@2.7.2

THX !

**Comment by divemasterjm** [comment]
me too

**Comment by cyberhusky69** [comment]
Hello
After installing version 2.8.0 it worked once. I saw my pws via WU. When I updated/upgraded the Linux installation, homebridge didn't start. Reinstalled homebridge and a new config. Hombridge starts and shows the QR code just to exit and restart every 10 secondsor so.
After reverting to 2.7.2 homebridge runs ok again. Though NO WU PWS :-(

BTW how can I check if I do have more than one instances of the homebridge running?
thx

**Comment by TNTLarsn** [comment]
same issues here

**Comment by naofireblade** [comment]
Thanks for reporting. Nothing has changed in the openweathermap api. I will check and fix this asap.

**Comment by naofireblade** [comment]
Got it. This was broken by a recent pull request.

**Comment by naofireblade** [comment]
Fixed in v2.8.1

@cyberhusky69 Please open another ticket if you still have issues. I'm not sure if your issue is the same as this one.

**Comment by JacVid** [comment]
THX, it works now ! 👍

**Comment by det-box** [comment]
Thanks, it's working again.

**Comment by cyberhusky69** [comment]
THX it works now!
